#!/bin/bash
. ./cleanAll
echo "Generating project deliverable : Millat-Plougonven.SIT213.EtapeX.tar.gz"
tar -czf Millat-Plougonven.SIT213.EtapeX.tar.gz src bin docs tests simulateur compile runTests genDoc cleanAll ai_prompts.md README.md
echo "Done !"