#!/bin/bash
. ./cleanAll
echo "Generating project deliverable : Millat-Plougonven.SIT213.Etape.tar.gz"
tar -czf Millat-Plougonven.SIT213.Etape.tar.gz src bin docs compile runTests genDoc cleanAll ai_prompts.md README.md
echo "Done !"